### ISSUE TITLE
Downloading v0.8.1 all the files don't extract due to "virus" found

### ISSUE THREAD

**Issue by staticfrost** [stellitecoin/StelliteGUI#13]
Downloading v0.8.1 all the files don't extract due to "virus" found

**Comment by hayzamjs** [comment]
False positive, try white listing.

**Comment by staticfrost** [comment]
That's not the solution. Try package the app so its not listed as a virus?

**Comment by Endogen** [comment]
It's not like that's possible. Some antivirus software just generally identifies some specific software as a malware / miner and thus will block it. Not much the devs can do about it. Especially because the wallet has an integrated miner.

If you don't trust the project, maybe you trust Monero? If so, try to download their wallet - since it's basically the same - and let's see if they have the same issue. I guarantee you will have the same issue there too. It's not like this is Stellite specific
