### ISSUE TITLE
Win 64x Stellite GUI 1.0.2 Wallet- Disconnected

### ISSUE THREAD

**Issue by lasvegascjones** [stellitecoin/StelliteGUI#24]
Stellite wallet was working great. Now the status is Disconnected. I have manually tried to start Daemon. Continue to get message "Daemon failed to start". Verified antivirus permissions were given. I also completly removed the wallet and reloaded it with Mnemonic Seed.

**Comment by Endogen** [comment]
Do you use a remote node? If yes, maybe the node isn't available anymore, try another one

**Comment by lasvegascjones** [comment]
Not sure? How do I change to another one?

**Comment by lasvegascjones** [comment]
It seems like its working. It does say it's CONNECTED and i'm seeing that
is updating the Blocks Remaining.  Thank you very much for your help. Is
there something I would have done to create this problem?

**Comment by Endogen** [comment]
Not sure but i guess not. Using a remote node means that you don't have to download the whole blockchain anymore and you rely on a remote node to provide you the necessary info. So before that you did download the whole chain and it seems something was wrong with that.

Please close the issue if possible since it's resolved. Thanks
